timezone: "Europe/Brussels"

filters:
  keywords:
    - "bouwgrond"
    - "bouwperceel"
    - "projectgrond"
    - "huis met grote tuin"
  locations:
    - "Oost-Vlaanderen"
    - "Vlaams-Brabant"
  price_max_eur: 450000

sites:
  - name: "Immoscoop — Bouwgrond (lijst)"
    adapter: "immoscoop_list"
    start_urls:
      - "https://www.immoscoop.be/zoeken/te-koop/9340-oordegem,9230-westrem,lede,wetteren,wichelen/bouwgrond?fronts=open&maxPrice=325000"
