# === Configuration ===
timezone: "Europe/Brussels"

filters:
  keywords:
    - "bouwgrond"
    - "bouwperceel"
    - "projectgrond"
    - "huis met grote tuin"
  locations:
    - "Oost-Vlaanderen"
    - "Vlaams-Brabant"
  price_max_eur: 450000

sites:
  - name: "Immoscoop — Bouwgrond"
    adapter: "generic_css"
    start_urls:
      - "https://www.immoscoop.be/zoeken/te-koop/op-kaart/bouwgrond?geoShape=cieh%2560BgqwkFjra%40fyrApwqAkhq%40kgq%40umaEscrAvcrA%2560%2560O%2560xlA&fronts=open&maxPrice=325000"
    selectors:
      list: "a[data-mobile-selector='property-card_card']"
      title: ".property-card_title::text"
      url: "::attr(href)"
      location: ".property-card_address::text"
      price: ".property-card_price::text"
      url_prefix: "https://www.immoscoop.be"
    date_hints:
      - "DD/MM/YYYY"
      - "D MMM YYYY"
      - "gisteren"
      - "vandaag"

 - name: "Immoscoop — Bouwgrond (lijst)"
  adapter: "generic_css"
  start_urls:
    - "https://www.immoscoop.be/zoeken/te-koop/9340-oordegem,9230-westrem,lede,wetteren,wichelen/bouwgrond?fronts=open&maxPrice=325000"
  selectors:
    # Het kaartje is een <a>; deze pakt elk pandkaartje
    list: "a[data-mobile-selector='property-card_card']"
    title: ".property-card_title::text"
    url: "::attr(href)"                 # href van het <a>-element zelf
    location: ".property-card_address::text"
    price: ".property-card_price::text"
    url_prefix: "https://www.immoscoop.be"
  date_hints:
    - "DD/MM/YYYY"
    - "D MMM YYYY"
    - "gisteren"
    - "vandaag"
