timezone: "Europe/Brussels"

filters:
  keywords:
    - "bouwgrond"
    - "bouwperceel"
    - "projectgrond"
    - "huis met grote tuin"
  locations:
    - "Oost-Vlaanderen"
    - "Vlaams-Brabant"
  price_max_eur: 450000

sites:
  - name: "Immoscoop — Bouwgrond (lijst)"
    adapter: "generic_css"
    start_urls:
      - "https://www.immoscoop.be/zoeken/te-koop/9340-oordegem,9230-westrem,lede,wetteren,wichelen/bouwgrond?fronts=open&maxPrice=325000"
    selectors:
      list: "div[data-component='paginated-page-list_items'] a[href^='/te-koop/']"
      title: ".property-card_title::text"
      url: "::attr(href)"
      location: ".property-card_address::text"
      price: ".property-card_price::text"
      url_prefix: "https://www.immoscoop.be"
    date_hints:
      - "DD/MM/YYYY"
      - "D MMM YYYY"
      - "gisteren"
      - "vandaag"
